version: '2'
services:
  container:
    image: opentosca/container
    ports:
      - '1337:1337'
    environment:
      - CONTAINER_HOSTNAME=container
      - CONTAINER_REPOSITORY_HOSTNAME=container-repository
      - ENGINE_PLAN_HOSTNAME=engine-plan
      - ENGINE_IA_HOSTNAME=engine-ia
    networks:
      - opentosca
    restart: unless-stopped
  container-repository:
    image: opentosca/winery
    ports:
      - '8081:8080'
    volumes:
      - /var/opentosca/container/repository:/var/opentosca/repository
    networks:
      - opentosca
    restart: unless-stopped
  ui:
    image: opentosca/ui
    ports:
      - '8088:8080'
    networks:
      - opentosca
    restart: unless-stopped
  engine-plan:
    image: opentosca/engine-plan
    ports:
      - '9443:9443' # https
      - '9763:9763' # http
    environment:
      - ENGINE_PLAN_HOSTNAME=engine-plan
    networks:
      - opentosca
    restart: unless-stopped
  engine-ia:
    image: opentosca/engine-ia
    ports:
      - '8090:8080'
    networks:
      - opentosca
    restart: unless-stopped
  winery:
    image: opentosca/winery
    ports:
      - '8080:8080'
    volumes:
      - /var/opentosca/winery/repository:/var/opentosca/repository
    networks:
      - opentosca
    restart: unless-stopped
  portainer:
    image:  portainer/portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - '9000:9000'
    volumes:
      - /var/opentosca/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - opentosca
    restart: unless-stopped
networks:
  opentosca:
    driver: bridge
